### ISSUE TITLE
Bugs & Suggestions

### ISSUE THREAD

**Issue by Rayjiun** [Blakintosh/gscode#5]
A list of bugs & suggestions.
This issue aside, the work is absolutely fantastic and I'm excited to see the other features release once it comes out of a beta.
Thank you for the hard work!

p.s. Do you have a donation link?

# Bugs

### Function call when sent as a parameter seems to sometimes be funky. See 2 examples below.
_Refer to `GetTagOrigin` call_
![image](https://github.com/user-attachments/assets/ef1c7614-2764-457f-a777-9505a41212f1)

_Refer to `GetMins` call_
![image](https://github.com/user-attachments/assets/cef76e4d-0b9c-44d7-b96d-ef0d625e9308)

Above function calls highlight perfectly when otherwise called.

### Macros when called inside of a macro function has improper highlighting
_Refer to `MALIGNENT_DEATH_NOTETRACK` macro_
![image](https://github.com/user-attachments/assets/f8c21446-8743-43d8-b0ab-8401e1a5bac3)

### Macro functions seem to have some issues

Can't diagnose exactly why, my best guess is the vectors.

Refer to `SPHERE` and `LINE` calls
![image](https://github.com/user-attachments/assets/834b845d-1510-42b4-9180-9af205a56be5)
![image](https://github.com/user-attachments/assets/4c9a2b5f-ebcb-4eaa-9c53-89749881afb9)

### Array references highlighted wrong

When sending an array reference, if named array it highlights wrongfully as it thinks it's a function call. 
Normal variable name works, but when paired with `&` operator, it highlights.

_See below examples (can be found in `scripts/shared/array_shared`)_
![image](https://github.com/user-attachments/assets/fc88f894-fa5e-4f88-afa7-7fbe66868ef1)
![image](https://github.com/user-attachments/assets/7375e964-469b-4e4b-ac2e-bd1d6e2c8be0)

### (Unsure if bug) Highlighting when it sees problems in the file disappears when you collapse folder

For example
![image](https://github.com/user-attachments/assets/a2d9b327-8a2a-41cc-824c-2bedfba5386c)

It highlights it in orange, saying there's issues.
But when I collapse, the orange highlighting disappears.

![image](https://github.com/user-attachments/assets/ca144573-d8b7-4293-af69-aea6788c9377)

# Suggestions

### Developer blocks
As of now, developer blocks do not have any unique sort of highlighting or showcase inside of the addon itself to show that it's a dev block.
Obviously, the `/# #/` syntax is still present, but with previous addons made by other creators these were highlighted.
I never was a fan of how they highlighted it as a comment block, but it'd be nice to somehow make note of it through giving a unique highlighting to the dev block itself.

_See example code_
![image](https://github.com/user-attachments/assets/32e65c12-d2e1-4738-98d0-e486c9e8b4a9)

### Highlighting
Small question, but how come IsDefined isn't just treated as a function?
Functions currently (with my theme) are highlighted in yellow, but IsDefined is purple.
![image](https://github.com/user-attachments/assets/81697846-da30-4466-875a-f47bdba380b5)

**Comment by Rayjiun** [comment]
Re: _Array references highlighted wrong_
This seems to be an issue with every variable name that has the same name as a function.
![image](https://github.com/user-attachments/assets/a96bc394-cdf6-4b5e-9d74-f10648d2e050)

**Comment by Blakintosh** [comment]
Thanks for the kind words and for these finds!

I'm working on v0.1.2 to fix the bugs you've found, and I've now squashed most of those issues. There were a few issues in the patterns of the syntax highlighter, and the preprocessor wasn't handling vectors properly because it wasn't checking for punctuation on the first token of macro arguments. Those are now fixed, and I just have the macro inside macro semantic highlighting issue to solve left.

On the file tree, I'm not super familiar on what the standard vscode behaviour is, but it's worth mentioning that the extension should behave in line with other language extensions on opened editors. That said, it's configured to publish diagnostics only for editors that are currently open, and this probably won't change.

Do you have any suggestions on how we should highlight the dev blocks? I agree that highlighting them like comments wouldn't fit, but I'm not entirely sure on what _would_ be the best fit. The two real options we probably have are pink or dark blue, with possibly a base highlight for the contents too. See below
![Screenshot 2024-11-22 at 16 28 55](https://github.com/user-attachments/assets/0dac7334-3959-46ff-88d7-edf167ff358f)
![Screenshot 2024-11-22 at 16 29 53](https://github.com/user-attachments/assets/078e7f00-fb21-4f8b-ad00-234ab2fd3229)

**Comment by Scobalula** [comment]
Yes, isdefined is not a function, it's a keyword with it's own vm instruction.

**Comment by Rayjiun** [comment]
Thanks for the reply @Blakintosh - all looks good! I like the pink (purple?), not like it matters much but it's a nice little indicator to signify it's  something special. 

Good to know on the IsDefined instruction though. Thanks! Learned something.

**Comment by Blakintosh** [comment]
@Rayjiun v0.1.2 is now released which should hopefully have addressed all the issues you've found. Agreed on the pink and that's what I've gone with. If you spot any more issues, please do send those through!
